export const GET_EMPLOYEES = 'GET_EMPLOYEES';

export const GET_CONSULTANCYPROJECTS = 'GET_CONSULTANCYPROJECTS';

export const GET_RELATEDCONSULTS = 'GET_RELATEDCONSULTS';

//used in getting the consult details based on ID
export const GET_CONSULT_DEATILS = 'GET_CONSULT_DEATILS';

export const GET_CONSULT_INFO = 'GET_CONSULT_INFO';

export const DELETE_CONSULTANT = 'DELETE_CONSULTANT';

//clint view consults
export const GET_RELATEDCLIENTCONSULTS = 'GET_RELATEDCLIENTCONSULTS';

export const GET_RELATEDCONSULTSINFO = 'GET_RELATEDCONSULTSINFO';

//admin
export const GET_ALLCONSULTANCYPROJECTS = 'GET_ALLCONSULTANCYPROJECTS';
