export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
export const UPDATE_PROJECT_DETAILS = "UPDATE_PROJECT_DETAILS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_RELATEDPROJECTS = "GET_RELATEDPROJECTS"
