export const GET_TICKETS = 'GET_TICKETS';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';

export const GET_EMPLOYEETICKET = 'GET_EMPLOYEETICKET';

export const GET_CLIENTTICKET = 'GET_CLIENTTICKET';

export const GET_CLIENTTICKETBYID = 'GET_CLIENTTICKETBYID';



